create table service_provider
(
    service_provider_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name                VARCHAR(100) NOT NULL,
    bank_name           VARCHAR(100) NOT NULL,
    bank_bik            VARCHAR(100) NOT NULL,
    account_number      VARCHAR(100) NOT NULL
);

CREATE TABLE service_consumer
(
    service_consumer_id SERIAL PRIMARY KEY,
    service_provider_id         INT          REFERENCES service_provider (service_provider_id) ON DELETE SET NULL,
    full_name           VARCHAR(255) NOT NULL,
    account_number      VARCHAR(50) UNIQUE
);

CREATE TABLE payment
(
    payment_id    SERIAL PRIMARY KEY,
    consumer_id   INT REFERENCES service_consumer (service_consumer_id) ON DELETE CASCADE,
    amount        DECIMAL(10, 2) NOT NULL,
    payment_date  DATE           NOT NULL,
    transfer_mark BOOLEAN DEFAULT FALSE
);

CREATE TABLE fund_transfer
(
    fund_transfer_id SERIAL PRIMARY KEY,
    provider_id      INT REFERENCES service_provider (service_provider_id) ON DELETE CASCADE,
    amount           DECIMAL(10, 2) NOT NULL,
    transfer_date    DATE           NOT NULL
);